sonar.projectKey=fuchi-no-dokuneko_RecorderLong
sonar.organization=fuchi-no-dokuneko
sonar.host.url=https://sonarcloud.io
sonar.projectName=RecorderLong
sonar.sourceEncoding=UTF-8
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.java.binaries=app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes,app/build/tmp/kotlin-classes/debug
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest,app/build/outputs/androidTest-results/connected/debug
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml,app/build/reports/coverage/androidTest/debug/connected/report.xml
sonar.androidLint.reportPaths=app/build/reports/lint-results-debug.xml
