sonar.projectKey=fuchi-no-dokuneko_RecorderLong
sonar.organization=fuchi-no-dokuneko
sonar.host.url=https://sonarcloud.io
sonar.projectName=RecorderLong
sonar.sourceEncoding=UTF-8
sonar.sources=app/src/main/java,tools
sonar.tests=app/src/test/java,app/src/androidTest/java,tools/tests,acceptance/features
sonar.exclusions=tools/tests/**,tools/**/__pycache__/**
sonar.java.binaries=app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest,app/build/outputs/androidTest-results/connected/debug
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml,app/build/reports/coverage/androidTest/debug/connected/report.xml
sonar.python.coverage.reportPaths=build/reports/python/coverage.xml
sonar.androidLint.reportPaths=app/build/reports/lint-results-debug.xml
